### PR TITLE
Codecov [WIP]

### PR DESCRIPTION
**Pull request by optiomas**

### CODE REVIEW

**Comment by optiomas** [comment]
@hashmap: Sure thing. We just need to set some team norms around WIP. The new `CODEOWNERS` file makes an open PR automatically assign reviewers. This is undesirable for experiments, temporary things or just any sort of WIP. Is this rationale clear?

**Comment by optiomas** [comment]
There's [WIP] in the PR title, if it wasn't obvious :)

**Comment by hashmap** [comment]
I understand, but what is the rationale to send a PR? At least to get a feedback, otherwise, a local branch is good enough. It requires some context, so I'd expect a commit message. Also WIP usually means 'do not merge'.

**Comment by optiomas** [comment]
WIP means Work In Progress. A PR is needed in this case to test integration with third party services via Github's webhooks and commit status where a local branch isn't enough.

**Pull request closed without merging**
