### PR TITLE
a token Signer can create a Verifier to verifiy its own tokens

### PR DESCRIPTION
**Pull request by jeremyhuiskamp**
In the case where we want to create both a signer and a verifier at
the same time, it's much simpler to just pull the public key from
the private one, instead of managing the public key separately.

### CODE REVIEW

**Comment by alpe** [comment]
I could not review just the diff because I was missing context. There are no blockers in this PR but I'd suggest that:
* we do less documentation but have verbose method names. Adding RSA would be more descriptive as part of the factory method names as no other type is supported
* don't do named return values https://github.com/golang/go/wiki/CodeReviewComments
* instead of `Generate` and `Parse` `Marshal` and `Unmarshal` would be closer to the stdlib naming

**Comment by jeremyhuiskamp** [comment]
Agreed on the method names, especially since they don't match the struct names.  And `Signer` and `Verifier` are a bit lacking since they do more than that.  A brief survey of `encoding/*` packages suggests that `Encode` / `Decode` are a bit more idiomatic so I'll maybe go with that (in `xml` and `json`, `Marshaler` and `Unmarshaler` are interfaces for objects that operate on themselves).

I'm all for adding `RSA` to the factory names, but I don't want to remove the documentation.  Having `RSA` in the name is good when you're reading code that calls this api, but it doesn't completely explain what it means ("any other algorithm isn't supported"), given that the api contract doesn't prevent passing other types of keys in.

I will merge this PR and create another one to follow up on your suggestions.

**Comment by alpe** [comment]
@satran is there any reason why we don't use the `v2` version of that lib?

**Comment by jeremyhuiskamp** [comment]
@alpe: I suspect the reason for using `v1` is that the jose documentation recommends it as the current stable version.  I don't think `v2` is ready yet.

**Pull request merged**
