### PR TITLE
nicer logview output

### PR DESCRIPTION
**Pull request by husio**

### CODE REVIEW

**Comment by optiopay-backend-helper** [comment]
Pull request seem to be stale, assigning @alpe as the responsible developer.

**Comment by alpe** [comment]
I can't find any tests. What's the policy with this project?

**Comment by optiopay-backend-helper** [comment]
Pull request seem to be stale, assigning @PragmaticCypher as the responsible developer.

**Comment by satran** [comment]
I would have liked to have a toggle to enable colors like `ls --color`. You know im not fond of colors :)

**Comment by husio** [comment]
I really don't care if it will get merged..

**Pull request closed without merging**
